<a href="https://colab.research.google.com/github/emisseldine/OpenLinear/blob/main/Chapter1/workbooks/aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<p style="text-align:center">
    <a href="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" target="_blank">
    <img src="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" width="200" alt="Missel Books Logo">
    </a>
</p>


# 2.2 Augmented Matrices
</center>

###For Exercises 1-4 below, write the linear system as augmented matrix or vice versa.


---


*An example is provided in Exercise 0. To execute your code, hit the play/execute/run button or Ctrl+Shift.*


0.   Write the linear system as augmented matrix:
$\begin{cases}
\qquad\quad~4x_2+2x_3 &=~~6\\
3x_1+~~5x_2+2x_3 &=~~7\\
3x_1+17x_2+8x_3 &=24
\end{cases}$





In [5]:
import numpy as np

print(np.array([[0,4,2,6],[3,5,2,7],[3,17,8,24]]))

[[ 0  4  2  6]
 [ 3  5  2  7]
 [ 3 17  8 24]]


1.   Write the linear system as augmented matrix:
$\begin{cases}
3x-~~y &=~~0\\
~~~~ -2y &=~~5\\
~~x+7y &=13
\end{cases}$


In [ ]:
### EXERCISE 1#######################################
print('Augmented Matrix') #report solution here

<details><summary>Click here for the solution</summary>

```python
print(np.array([[3,-1,0],[0,-2,5],[1,7,13]))
```
$\begin{bmatrix} 3&-1&0\\0&-2&5\\1&7&13\end{bmatrix}$

</details>

2.   Write the linear system as augmented matrix:
$\begin{cases}
\quad~x+~~y+z &=~~1\\
-2x-6y+z &=12
\end{cases}$


In [ ]:
### EXERCISE 2#######################################
print('Augmented Matrix') #report solution here

<details><summary>Click here for the solution</summary>

$\begin{bmatrix} 1&1&1&1\\-2&-6&1&12\end{bmatrix}$

</details>

3.   Write the augmented matrix as a linear system:
$\left[\begin{array}{rrr|r}
3&-2&-1&4\\
1&0&3&-3\\
0&0&0&2
\end{array}\right]$


In [ ]:
### EXERCISE 3#######################################
print('Linear System') #you may use '\n' for linebreaks

<details><summary>Click here for the solution</summary>

```python
print('3x-2y-z=4\nx+3z=-3\n0=2')
```
$\begin{cases}
3x-2y-~~z&=~~~4\\
~~x\qquad~+3z&=-3\\
\hfill0&=~~~2
\end{cases}$

</details>

4.   Write the augmented matrix as a linear system:
$\left[\begin{array}{rrrr|r}
4&-1&-2&5&12\\
-3&0&0&1&5\\
1&0&0&0&0
\end{array}\right]$


In [ ]:
### EXERCISE 4#######################################
print('Linear System') #report solution here

<details><summary>Click here for the solution</summary>

$\begin{cases}
~~~4x_1-x_2-2x_3+5x_4 &=12\\
-3x_1 \qquad\qquad\quad+~x_4 &=~~5\\
~~~~~x_1 &=~~0
\end{cases}$

</details>

---

### For Exercises 5-10, identify if the matrix is in echelon form and if it is in row reduced echelon form. If in echelon form, identify the pivot positions and the rank of the matrix.

5.  $\left[\begin{array}{rrrr|r}
1&2&3&4&5\\
0&6&7&8&9\\
0&0&0&3&4
\end{array}\right]$


In [ ]:
### EXERCISE 5#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

$\left[\begin{array}{rrrr|r}
\fbox{1}&2&3&4&5\\
0&\fbox{6}&7&8&9\\
0&0&0&\fbox{3}&4
\end{array}\right]$
echelon form, rank 3

</details>

6.  $\left[\begin{array}{rrrr|r}
1&2&3&4&5\\
0&1&7&8&9\\
0&0&0&0&2
\end{array}\right]$


In [ ]:
### EXERCISE 6#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

$\left[\begin{array}{rrrr|r}
\fbox{1}&2&3&4&5\\
0&\fbox{1}&7&8&9\\
0&0&0&0&2
\end{array}\right]$
echelon form, rank 2
</details>

7.  $\left[\begin{array}{rrrr|r}
1&2&3&4&5\\
0&0&0&0&2\\
0&6&7&8&9
\end{array}\right]$


In [ ]:
### EXERCISE 7#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

not ecehlon form

</details>

8.  $\left[\begin{array}{rrrr|r}
1&0&3&0&5\\
0&1&7&0&9\\
0&0&0&1&2
\end{array}\right]$


In [ ]:
### EXERCISE 8#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

$\left[\begin{array}{rrrr|r}
\fbox{1}&0&3&0&5\\
0&\fbox{1}&7&0&9\\
0&0&0&\fbox{1}&2
\end{array}\right]$
RREF, rank 3
</details>

9.  $\left[\begin{array}{rrrr|r}
1&0&3&4&5\\
0&1&7&8&9\\
0&0&0&0&2
\end{array}\right]$


In [ ]:
### EXERCISE 9#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

$\left[\begin{array}{rrrr|r}
\fbox{1}&0&3&4&5\\
0&\fbox{1}&7&8&9\\
0&0&0&0&2
\end{array}\right]$
RREF, rank 2
</details>

10.  $\left[\begin{array}{rrrr|r}
1&0&0&4&5\\
0&0&1&0&2\\
0&1&0&8&9
\end{array}\right]$


In [ ]:
### EXERCISE 10#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

not echelon form

</details>

---

### For Exercises 11-13, perform the indicated elementary row operation(s) to the augmented matrix.

11.  $\left[\begin{array}{rrr|r}
0&2&5&10\\
1&-1&3&6\\
2&7&-1&0
\end{array}\right]$\
interchange Rows 1 and 2


In [ ]:
### EXERCISE 11#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

$\left[\begin{array}{rrr|r}
1&-1&3&6\\
0&2&5&10\\
2&7&-1&0
\end{array}\right]$
</details>

12.  $\left[\begin{array}{rr|r}
3&-1&0\\
0&-2&5\\
1&7&13
\end{array}\right]$\
scale Row 2 by -1/2


In [ ]:
### EXERCISE 12#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

$\left[\begin{array}{rr|r}
3&-1&0\\
0&1&-2.5\\
1&7&13
\end{array}\right]$
</details>

13.  $\left[\begin{array}{rrr|r}
1&1&1&1\\
-2&-6&1&12
\end{array}\right]$\
replace Row 2 with Row 2 + 2 Row 1

In [ ]:
### EXERCISE 13#######################################
print('Solution') #report solution here

<details><summary>Click here for the solution</summary>

$\left[\begin{array}{rrr|r}
1&1&1&1\\
0&-4&3&14
\end{array}\right]$
</details>

*When completed, download the notebook as a .pdf file and upload it to the course's learning management system, e.g. Canvas. To do this, via Google Chrome, choose `File`, then `Print` (or simply `Ctrl+P`). Then choose printer `Destination` as `Print as PDF.` You may have to adjust setting to print well. For example, set `Layout` as `Landscape` and under `More Settings` turn off `Headers and Footers`.*



---
<center>

##### This Python workbook was produced for [Linear Algebra Done Openly](https://github.com/emisseldine/OpenLinear) by Dr. Andrew Misseldine (2026).
<p style="text-align:center">
    <a href="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" target="_blank">
    <img src="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" width="200" alt="Missel Books Logo">
    </a>
</p>
</center>