<a href="https://colab.research.google.com/github/emisseldine/OpenLinear/blob/main/Chapter1/workbooks/echelon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<p style="text-align:center">
    <a href="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" target="_blank">
    <img src="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" width="200" alt="Missel Books Logo">
    </a>
</p>


# 2.3 Reduction of Linear Systems
</center>

###For Exercises 1-3 below, compute the row reduced echelon form for the matrix. List the row operations used to transform the matrix to this form. Indicate the first time the matrix is in echelon form. Answers may vary.


---


*An example is provided in Exercise 0. To execute your code, hit the play/execute/run button or Ctrl+Shift.*


0.   $\begin{bmatrix}
1&2\\
-4&5
\end{bmatrix}$





In [25]:
import numpy as np

A = np.array([[1,2],[-4,5]])
print(A,'\n')

# replace Row 2 with Row 2 + 4 Row 1
A[1] = A[1] + 4*A[0]
print(A, '\n replace Row 2 with Row 2 + 4 Row 1\n echelon form\n')

# scale Row 2 by 1/13
A[1] = A[1]/13
print(A, '\n scale Row 2 by 1/13\n')

# replace Row 1 with Row 1 - 2 Row 2
A[0] = A[0] - 2*A[1]
print(A, '\n replace Row 1 with Row 1 - 2 Row 2\n RREF')

[[ 1  2]
 [-4  5]] 

[[ 1  2]
 [ 0 13]] 
 replace Row 2 with Row 2 + 4 Row 1
 echelon form

[[1 2]
 [0 1]] 
 scale Row 2 by 1/13

[[1 0]
 [0 1]] 
 replace Row 1 with Row 1 - 2 Row 2
 RREF


1.   $\begin{bmatrix}
1&2&3\\
2&3&3\\
2&4&5
\end{bmatrix}$

In [ ]:
### EXERCISE 1#######################################
A = np.array([[1,2,3],[2,3,3],[2,4,5]])
print(A,'\n')

# first row operation

print(A, '\n first row operation\n')

<details><summary>Click here for the solution</summary>

```python
A = np.array([[1,2,3],[2,3,3],[2,4,5]])
print(A,'\n')

# replace Row 2 with Row 2 - 2 Row 1
A[1] = A[1] - 2*A[0]
# replace Row 3 with Row 3 - 2 Row 1
A[2] = A[2] - 2*A[0]
print(A, '\n replace Row 2 with Row 2 - 2 Row 1\n replace Row 3 with Row 3 - 2 Row 1\n echelon form\n')

# scale Row 2 by -1
A[1] = -1*A[1]
# scale Row 3 by -1
A[2] = -1*A[2]
print(A, '\n scale Row 2 by -1\n scale Row 3 by -1\n')

# replace Row 1 with Row 1 - 3 Row 3
A[0] = A[0] - 3*A[2]
# replace Row 2 with Row 2 - 3 Row 3
A[1] = A[1] - 3*A[2]
print(A, '\n replace Row 1 with Row 1 - 3 Row 3\n replace Row 2 with Row 2 - 3 Row 3\n')

# replace Row 1 with Row 1 - 2 Row 2
A[0] = A[0] - 2*A[1]
print(A, '\n replace Row 1 with Row 1 - 2 Row 2\n RREF')
```
$\begin{bmatrix}
\fbox1&2&3\\
0&\fbox{$-1$}&-3\\
0&0&\fbox{$-1$}
\end{bmatrix}
\sim
\begin{bmatrix}
\fbox1&0&0\\
0&\fbox1&0\\
0&0&\fbox1
\end{bmatrix}$
</details>

2.   $\begin{bmatrix}
1&2&2&1\\
2&1&-2&-2\\
1&-1&-4&-3
\end{bmatrix}$

In [ ]:
### EXERCISE 2#######################################
A = np.array([[1,2,2,1],[2,1,-2,-2],[1,-1,-4,-3]])
print(A,'\n')

# first row operation

print(A, '\n first row operation\n')

<details><summary>Click here for the solution</summary>

$\begin{bmatrix}
\fbox1&2&2&1\\
0&\fbox{$-3$}&-6&-4\\
0&0&0&0
\end{bmatrix}
\sim
\begin{bmatrix}
\fbox1&0&-2&-\frac{5}{3}\\
0&\fbox1&2&\frac{4}{3}\\
0&0&0&0
\end{bmatrix}$

replace Row 2 with Row 2 - 2Row 1,

replace Row 3 with Row 3 - Row 1,

replace Row 3 with Row 3 - Row 2,

scale Row 2 by -1/3,

replace Row 1 with Row 1 - 2Row 2

</details>

3.   $\begin{bmatrix}
1&5&6&-5\\
3&0&-2&1\\
0&1&3&3\\
-3&5&0&1
\end{bmatrix}$


In [ ]:
### EXERCISE 3#######################################
A = np.array([[1,5,6,-5],[3,0,-2,1],[0,1,3,3],[-3,5,0,1]])
print(A,'\n')

# first row operation

print(A, '\n first row operation\n')

<details><summary>Click here for the solution</summary>

$\begin{bmatrix}
\fbox1&5&6&-5\\
0&\fbox1&3&3\\
0&0&\fbox{25}&61\\
0&0&0&\fbox{$\frac{712}{25}$}
\end{bmatrix}
\sim
\begin{bmatrix}
\fbox1&0&0&0\\
0&\fbox1&0&0\\
0&0&\fbox1&0\\
0&0&0&\fbox1
\end{bmatrix}$

replace Row 2 with Row 2 - 3 Row 1,

replace Row 4 with Row 4 + 3 Row 1,

interchange Rows 2 and 3,

replace Row 3 with Row 3 + 15 Row 2,

replace Row 4 with Row 4 - 20 Row 2,

replace Row 4 with Row 4 + 42/25 Row 3,

scale Row 4 by 25/712,

replace Row 1 with Row 1 + 5 Row 4,

replace Row 2 with Row 2 - 3 Row 4,

replace Row 3 with Row 3 - 61 Row 4,

scale Row 3 by 1/25,

replace Row 1 with Row 1 - 6 Row 3,

replace Row 2 with Row 2 - 3 Row 3,

replace Row 1 with Row 1 - 5 Row 2
</details>

---

### For Exercises 4-7, solve the linear system.

4.  $\begin{cases}
x+y &=8\\
x-y &=4
\end{cases}$


In [ ]:
### EXERCISE 4#######################################
A = np.array([[1,1],[1,-1]])
b = np.array([8,4])

print() #compute the solution here

<details><summary>Click here for the solution</summary>

```python
print(np.linalg.solve(A,b))
```
$(6,2)$
</details>

5.  $\begin{cases}
~~x-~~y &=~~6\\
2x\qquad-3z &=16\\
\qquad 2y+~~z &=~~4
\end{cases}$


In [ ]:
### EXERCISE 5#######################################
print() #compute the solution here

<details><summary>Click here for the solution</summary>

$(8,2,0)$
</details>

6.  $\begin{cases}
2x-2y-2z &=2\\
2x+3y+~~z &=2\\
3x+2y &=0
\end{cases}$


In [ ]:
### EXERCISE 6#######################################
print() #compute the solution here

<details><summary>Click here for the solution</summary>

inconsistent
</details>

7.  Solve the linear system $[A\ |\ \boldsymbol b]$.


In [ ]:
### EXERCISE 7#######################################
#Solve the linear system [A|b]
A = np.array([[6, 5, 0], [4, 0, 3], [0, 2, 1]])
b = np.array([13, 5, 5])

print() #compute the solution here

<details><summary>Click here for the solution</summary>

$(0.5,2,1)$
</details>

*When completed, download the notebook as a .pdf file and upload it to the course's learning management system, e.g. Canvas. To do this, via Google Chrome, choose `File`, then `Print` (or simply `Ctrl+P`). Then choose printer `Destination` as `Print as PDF.` You may have to adjust setting to print well. For example, set `Layout` as `Landscape` and under `More Settings` turn off `Headers and Footers`.*



---
<center>

##### This Python workbook was produced for [Linear Algebra Done Openly](https://github.com/emisseldine/OpenLinear) by Dr. Andrew Misseldine (2026).
<p style="text-align:center">
    <a href="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" target="_blank">
    <img src="https://raw.githubusercontent.com/emisseldine/OpenLinear/main/BackMatter/logo.png" width="200" alt="Missel Books Logo">
    </a>
</p>
</center>